# Generated by Django 5.0.6 on 2024-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashpensersubcategories',
            name='subcategory_type',
            field=models.CharField(blank=True, choices=[('Incomes', 'Incomes'), ('Expense', 'Expenses')], max_length=100, null=True),
        ),
    ]
